In [1]:
import torch
import torch.nn as nn

In [9]:
gru = nn.GRU(512, 512)

In [15]:
for a in gru.parameters():
    print(a.data)

tensor([[-0.0359, -0.0291,  0.0222,  ...,  0.0342, -0.0039,  0.0441],
        [ 0.0273, -0.0387,  0.0115,  ...,  0.0043, -0.0415,  0.0320],
        [ 0.0131, -0.0085,  0.0002,  ..., -0.0254, -0.0152,  0.0117],
        ...,
        [ 0.0270,  0.0213, -0.0384,  ...,  0.0217, -0.0255, -0.0206],
        [-0.0356, -0.0196, -0.0038,  ..., -0.0163,  0.0042, -0.0321],
        [ 0.0034, -0.0154,  0.0292,  ...,  0.0373,  0.0421,  0.0427]])
tensor([[ 0.0051, -0.0396,  0.0025,  ...,  0.0012,  0.0039,  0.0338],
        [ 0.0092, -0.0329, -0.0304,  ...,  0.0296, -0.0433,  0.0347],
        [-0.0397, -0.0156, -0.0427,  ..., -0.0074, -0.0056, -0.0280],
        ...,
        [-0.0170, -0.0007, -0.0062,  ...,  0.0184,  0.0157,  0.0345],
        [-0.0177,  0.0008, -0.0221,  ..., -0.0102,  0.0411,  0.0387],
        [-0.0374,  0.0156,  0.0396,  ...,  0.0290, -0.0420,  0.0049]])
tensor([-0.0155,  0.0334,  0.0277,  ..., -0.0182, -0.0362, -0.0360])
tensor([-0.0083,  0.0284, -0.0088,  ...,  0.0098,  0.0374,  0.0